
package com.capturemylog.ws.logdata;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "LogData", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://logcollectorazure.cloudapp.net/logdata.asmx?WSDL")
public class LogData
    extends Service
{

    private final static URL LOGDATA_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.capturemylog.ws.logdata.LogData.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.capturemylog.ws.logdata.LogData.class.getResource(".");
            url = new URL(baseUrl, "http://logcollectorazure.cloudapp.net/logdata.asmx?WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://logcollectorazure.cloudapp.net/logdata.asmx?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
        }
        LOGDATA_WSDL_LOCATION = url;
    }

    public LogData(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LogData() {
        super(LOGDATA_WSDL_LOCATION, new QName("http://tempuri.org/", "LogData"));
    }

    /**
     * 
     * @return
     *     returns LogDataSoap
     */
    @WebEndpoint(name = "LogDataSoap")
    public LogDataSoap getLogDataSoap() {
        return super.getPort(new QName("http://tempuri.org/", "LogDataSoap"), LogDataSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LogDataSoap
     */
    @WebEndpoint(name = "LogDataSoap")
    public LogDataSoap getLogDataSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "LogDataSoap"), LogDataSoap.class, features);
    }

}
